services:
  php:
    build: .
    container_name: sapling-php
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
  db:
    image: mariadb:11
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
  adminer:
    image: adminer:4
    container_name: sapling-adminer
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  dbdata: {}
