services:
  php:
    build: .
    container_name: twwp-core-php
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
  db:
    image: mariadb:11
    container_name: twwp-core-db
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - ./data-db:/var/lib/mysql
  adminer:
    image: adminer:4
    container_name: twwp-core-adminer
    ports:
      - "8081:8080"
    depends_on:
      - db
